version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./backend/dockerfiles/Dockerfile
    container_name: fastapi_todo_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/src
    working_dir: /src
    command: >
      uvicorn backend.src.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    container_name: todo_postgresql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pgdata:
